In [1]:
import tensorflow as tf 
print('tensorflow version - ', tf.__version__)

tensorflow version -  2.4.1


In [2]:
import numpy as np 
from random import randint 
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

In [3]:
train_labels = []
train_samples = []

In [4]:

# generating the data 

for i in range(50):
    # 5% of younger individuals who did experience side effects 
    random_younger = randint(13,64) 
    train_samples.append(random_younger)
    train_labels.append(1)

    # 5% of older individuals who did not experience side effects 
    random_older  = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)


for  i in range(1000):
    # the 95% younger individuals who did not experience side effects 
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(0)


    # the 95% of older individuals who did not experience side effects 
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(1)


In [5]:
#  converting the train data into array 
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)

train_labels,train_samples = shuffle(train_labels,train_samples)

In [6]:
scaler = MinMaxScaler(feature_range = (0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

**Simple tf.keras Sequencial Model**

In [7]:
from tensorflow import keras 
from tensorflow.keras.models import Sequential  
from tensorflow.keras.layers import Activation,Dense 
from tensorflow.keras.optimizers import Adam 
from tensorflow.keras.metrics import categorical_crossentropy

In [8]:
model = Sequential([
     Dense(units = 16, input_shape = (1,), activation = 'relu'),
     Dense(units = 32, activation = 'relu'),
     Dense(units = 2, activation = 'softmax')               
])


In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(optimizer=Adam(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics  = ['accuracy'])

In [11]:
model.fit(x = scaled_train_samples,
          y = train_labels,
          validation_split = 0.1,
          batch_size = 10, 
          epochs = 30, 
          shuffle = True,
          verbose = 2)

Epoch 1/30
189/189 - 1s - loss: 0.6418 - accuracy: 0.5513 - val_loss: 0.6358 - val_accuracy: 0.5810
Epoch 2/30
189/189 - 0s - loss: 0.6136 - accuracy: 0.6423 - val_loss: 0.6009 - val_accuracy: 0.7000
Epoch 3/30
189/189 - 0s - loss: 0.5810 - accuracy: 0.7333 - val_loss: 0.5694 - val_accuracy: 0.7333
Epoch 4/30
189/189 - 0s - loss: 0.5484 - accuracy: 0.7757 - val_loss: 0.5329 - val_accuracy: 0.7714
Epoch 5/30
189/189 - 0s - loss: 0.5110 - accuracy: 0.8206 - val_loss: 0.4950 - val_accuracy: 0.8190
Epoch 6/30
189/189 - 0s - loss: 0.4770 - accuracy: 0.8492 - val_loss: 0.4612 - val_accuracy: 0.8333
Epoch 7/30
189/189 - 0s - loss: 0.4453 - accuracy: 0.8582 - val_loss: 0.4287 - val_accuracy: 0.8857
Epoch 8/30
189/189 - 0s - loss: 0.4157 - accuracy: 0.8751 - val_loss: 0.3988 - val_accuracy: 0.8952
Epoch 9/30
189/189 - 0s - loss: 0.3892 - accuracy: 0.8868 - val_loss: 0.3720 - val_accuracy: 0.8952
Epoch 10/30
189/189 - 0s - loss: 0.3661 - accuracy: 0.8984 - val_loss: 0.3492 - val_accuracy: 0.9048

In [12]:
# generating the data 
test_labels = []
test_samples = []
for i in range(10):
    # 5% of younger individuals who did experience side effects 
    random_younger = randint(13,64) 
    test_samples.append(random_younger)
    test_labels.append(1)

    # 5% of older individuals who did not experience side effects 
    random_older  = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)


for  i in range(200):
    # the 95% younger individuals who did not experience side effects 
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)


    # the 95% of older individuals who did not experience side effects 
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)

In [13]:
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)
test_labels, test_samples = shuffle(test_labels, test_samples)

In [14]:
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

In [15]:
# prediction 
predictions = model.predict(x = scaled_test_samples, batch_size = 10, verbose = 0)

In [16]:
predictions

array([[0.03049275, 0.9695072 ],
       [0.02855349, 0.9714466 ],
       [0.85177594, 0.14822412],
       [0.9763575 , 0.02364246],
       [0.03255933, 0.9674406 ],
       [0.8324732 , 0.16752672],
       [0.2957711 , 0.7042289 ],
       [0.02502774, 0.9749723 ],
       [0.81121415, 0.18878591],
       [0.03049275, 0.9695072 ],
       [0.9223918 , 0.07760822],
       [0.9763837 , 0.02361634],
       [0.9763706 , 0.0236294 ],
       [0.07049647, 0.92950356],
       [0.97626585, 0.02373413],
       [0.81121415, 0.18878591],
       [0.02502774, 0.9749723 ],
       [0.8848597 , 0.11514035],
       [0.86920387, 0.13079616],
       [0.9763051 , 0.02369481],
       [0.2957711 , 0.7042289 ],
       [0.03476093, 0.96523905],
       [0.9763706 , 0.0236294 ],
       [0.07506426, 0.9249357 ],
       [0.93217796, 0.06782205],
       [0.03255933, 0.9674406 ],
       [0.7879443 , 0.21205564],
       [0.14936936, 0.85063064],
       [0.85177594, 0.14822412],
       [0.08502412, 0.9149759 ],
       [0.

In [17]:
rounded_predictions = np.argmax(predictions, axis = -1 )

In [18]:
rounded_predictions

array([1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,

In [19]:
%matplotlib inline 
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [20]:
cm = confusion_matrix(y_true=test_labels, y_pred = rounded_predictions)

In [21]:
cm

array([[195,  15],
       [ 10, 200]])