In [2]:
import tensorflow as tf

In [19]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [20]:
x = tf.constant(3,shape = (1,2), dtype = tf.float32)
print(x)

tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)


In [21]:
# from lists 
x = tf.constant([[1,2,3],[2,3,1]])
print(x)

tf.Tensor(
[[1 2 3]
 [2 3 1]], shape=(2, 3), dtype=int32)


In [22]:
tens = tf.ones((3,3))
print(tens)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [23]:
tens = tf.ones((2,4),dtype = 'int32')
print(tens)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]], shape=(2, 4), dtype=int32)


In [24]:
# identity tensor 
eye_tens = tf.eye(5)
print(eye_tens)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [25]:
x = tf.random.normal((3,2),mean = 0, stddev = 1)
print(x)

tf.Tensor(
[[-0.30548912  0.55104655]
 [-1.8291519  -0.10373098]
 [-0.19354954 -0.16960748]], shape=(3, 2), dtype=float32)


In [26]:
x = tf.random.uniform((4,1) , minval = 0, maxval = 9)
print(x)

tf.Tensor(
[[8.448562 ]
 [1.9103261]
 [5.9037824]
 [7.881711 ]], shape=(4, 1), dtype=float32)


In [27]:
x = tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [28]:
# casting 
c = tf.cast(x,dtype = tf.float32)
print(c)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


## **Tensor Operations**

In [29]:
# element wise operations 
x = tf.constant([1,2,3])
y = tf.constant([2,3,4])
z = tf.add(x,y)
print(z)

tf.Tensor([3 5 7], shape=(3,), dtype=int32)


In [31]:
f = tf.subtract(x,y)
print(f)

tf.Tensor([-1 -1 -1], shape=(3,), dtype=int32)


In [32]:
f = tf.divide(x,y)
print(f)

tf.Tensor([0.5        0.66666667 0.75      ], shape=(3,), dtype=float64)


In [34]:
m = tf.multiply(x,y)
print(m)

tf.Tensor([ 2  6 12], shape=(3,), dtype=int32)


In [36]:
d = tf.tensordot(x,y,axes = 1)
print(d)

tf.Tensor(20, shape=(), dtype=int32)


In [41]:
# multiplication with a constant 
print(m*2)

tf.Tensor([ 4 12 24], shape=(3,), dtype=int32)


In [43]:
tens1 = tf.random.normal((2,3))
tens2 = tf.random.normal((3,4))
z = tf.matmul(tens1,tens2)
print(z)

tf.Tensor(
[[ 0.66234875 -1.9203576  -1.6642896   0.18335585]
 [ 0.47399813 -2.324844   -1.4024776  -1.042882  ]], shape=(2, 4), dtype=float32)


## **Indexing and slicing**

In [52]:
# slicing and indexing 
t1 = tf.constant([[1,2,3,4],[3,4,5,2],[2,3,4,5]]) 
print(t1)

tf.Tensor(
[[1 2 3 4]
 [3 4 5 2]
 [2 3 4 5]], shape=(3, 4), dtype=int32)


In [56]:
# slicing and indexing are similar to numpy array 
print(t1[0,0])
print(t1[0:2,1:])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(
[[2 3 4]
 [4 5 2]], shape=(2, 3), dtype=int32)


In [58]:
# reshaping a tensor 
x = tf.random.normal((2,3))
print(x)

tf.Tensor(
[[ 0.8509728  -0.33786702 -0.15177879]
 [-0.2565188   0.766852    1.6029624 ]], shape=(2, 3), dtype=float32)


In [60]:
new_x = tf.reshape(x,(3,2))
print(new_x)

tf.Tensor(
[[ 0.8509728  -0.33786702]
 [-0.15177879 -0.2565188 ]
 [ 0.766852    1.6029624 ]], shape=(3, 2), dtype=float32)


In [61]:
# tensor is a kind of numpy array.
# we can convert tensor to numpy array and vice versa

In [62]:
x_numpy = new_x.numpy()
print(x_numpy)
print(type(x_numpy))

[[ 0.8509728  -0.33786702]
 [-0.15177879 -0.2565188 ]
 [ 0.766852    1.6029624 ]]
<class 'numpy.ndarray'>


In [63]:
x_numpy = tf.convert_to_tensor(x_numpy)
print(type(x_numpy))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [3]:
# getting a string tensor 
str_tens = tf.constant(['thomas','merin','joseph'])
print(str_tens)

tf.Tensor([b'thomas' b'merin' b'joseph'], shape=(3,), dtype=string)


In [4]:
# variable tensor 
x = tf.Variable([1,2,3])
print(x)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
